// Include the code generated by the build script
include!(concat!(env!("OUT_DIR"), "/detected_games.rs"));

/// Struct representing a game found in the repository
#[derive(Debug, Clone)]
pub struct GodotGame {
    pub name: &'static str,
    pub folder_name: &'static str,
}

/// The API function your launcher will call
pub fn get_available_games() -> Vec<GodotGame> {
    GAMES.iter()
        .map(|&folder| {
            // You can map the folder name to a pretty display name here if you want
            let name = match folder {
                "game_one" => "The First Chronicles",
                "game_two" => "Space Evaders",
                _ => folder, // Fallback to folder name
            };
            
            GodotGame {
                name,
                folder_name: folder,
            }
        })
        .collect()
}